apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-management
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-management
  template:
    metadata:
      labels:
        app: product-management
    spec:
      containers:
      - name: product-management
        image: product-management-service:latest
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: product-management
spec:
  selector:
    app: product-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
