apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-authentication
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-authentication
  template:
    metadata:
      labels:
        app: user-authentication
    spec:
      containers:
      - name: user-authentication
        image: user-authentication-service:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: user-authentication
spec:
  selector:
    app: user-authentication
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
